services:
  live-subprocess:
    build: .
    image: futureys/live-subprocess:development
    volumes:
      - .:/workspace:cached
      - /workspace/.venv
      - ./output:/output
      # - Using uv in Docker | uv
      #   https://docs.astral.sh/uv/guides/integration/docker/#caching
      - uv-cache:/root/.cache/uv
volumes:
  uv-cache:
