on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: read
jobs:
  call-workflow:
    uses: yukihiko-shinoda/reusable-workflow-invoke-lint-deploy/.github/workflows/workflow.yml@b7757fa239a31d979f38c07c1f2e5a6dacbc2f0c  # v1.0.0
    secrets:
      pypi_password: ${{ secrets.PYPI_PASSWORD }}
